name = "2025-11-25-advent-of-proof-2023"
version = "0.1.0"
defaultTargets = ["AdventOfProof"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "AdventOfProof"
